# -*- coding: utf-8 -*-
"""Train yolov5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PtntJkZ2zVz6Iy7RA_rCrraSrRJzquDp
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/baitap
!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/baitap/yolov5
# %pip install -qr requirements.txt  # install

import torch
from drive.MyDrive.baitap.yolov5 import utils
display = utils.notebook_init()  # checks

!unrar x "/content/drive/MyDrive/baitap/train_data.rar" "/content/drive/MyDrive/baitap/yolov5/data"

!python /content/drive/MyDrive/baitap/yolov5/train.py --img 640 --batch 16 --epochs 40 --data /content/drive/MyDrive/baitap/yolov5/data/custom_data.yaml --weights yolov5m.pt
